site_name: Name
site_description: Description
site_author: zkldi
site_url: example.com

theme:
  name: material
  palette:
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

nav:
  - Introduction: "index.md"

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
